name: telegram message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send photo message
      with:
        to: ${{ secrets.TGKEY }}
        token: ${{ secrets.TGCHANNELID }}
        message: send photo message
