name: telegram message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: ./
      with:
        to: ${{ secrets.TGKEY }}
        token: ${{ secrets.TGCHANNELID }}
        args: The ${{ github.event_name }} event triggered first step.